spring.application.name=netiot-service
spring.config.import=optional:file:.env[.properties]

server.port=${SERVER_PORT}

spring.datasource.url=jdbc:postgresql://${IP_DB}:${PORT_DB}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${SECRET_JWT}
jwt.expiration=${EXPIRATION_CODE_JWT}

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

spring.web.resources.static-locations=classpath:/static/

management.endpoints.web.exposure.include=health,info

server.error.include-stacktrace=never
server.error.include-message=never
