version: '3.8'

services:
  backend:
    image: JACPKET/controlador-iot:v1
    ports:
      - "8080:8080"
    networks:
      - red-iot
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: mi_iot_db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - red-iot

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      - red-iot

networks:
  red-iot:
    driver: bridge